let myName = "Adeel";
console.log(myName === "Adeel");
console.log(myName !== "Adeel");
console.log(myName.toLowerCase() === "adeel");
let num = 10;
console.log(num > 15);
console.log(num < 15);
console.log(num === 10);
console.log(num !== 10);
console.log(num >= 10);
console.log(num <= 10);
console.log(num >= 10 && num <= 10);
console.log(num >= 10 || num <= 10);
let arr = [1, 2, 3, 4, 5];
console.log(arr.indexOf(4) !== -1);
console.log(arr.indexOf(7) === -1);
export {};
